### PR TITLE
fix(go, java): synthesizing a go or java stack from a template with CFN properties of type json fails

### LINKED ISSUE #210: go: synthesizing a template with CFN properties of type json fails
a template including this:
```
"MyRDMessageQueueGroup" : {
      "Type" : "AWS::IAM::Group",
      "Properties" : {
        "Policies": [ {
          "PolicyName": "MyQueueGroupPolicy",
          "PolicyDocument": {
            "Statement":[ {
              "Effect":"Allow",
 	      "Action":[ "sqs:DeleteMessage", "sqs:ReceiveMessage" ],
              "Resource":[ { "Fn::GetAtt" : ["MyQueue1", "Arn"]}, { "Fn::GetAtt" : ["MyQueue2", "Arn"]} ]
            } ]
          }
        } ]
      }
    }
```
Will fail to synthesize to go with the error: 
```
thread 'main' panicked at 'internal error: entered unreachable code: object with simple structure (Json)', src/synthesizer/golang/mod.rs:637:29
```

This is because the type of a PolicyDocument is json ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-policy-2.html#cfn-iam-policies-policydocument)), and the go synthesizer doesn't currently handle this case https://github.com/iph/noctilucent/blob/e75176e31e4af8b157d28b825ea9f995e4c7bcae/src/synthesizer/golang/mod.rs#L631.

### PR DESCRIPTION
**Pull request by madeline-k**
fixes #210

### CODE REVIEW

File: src/synthesizer/golang/mod.rs [hunk 1]
```diff
@@ -620,25 +620,37 @@ impl GolangEmitter for ResourceIr {
...
+                        props.text(format!(
+                            "\"{name}\": ",
+                            name = golang_identifier(name, IdentifierKind::Exported)
+                        ));
+                    } else {
+                        props.text(format!(
+                            "{name}: ",
+                            name = golang_identifier(name, IdentifierKind::Exported)
+                        ));
+                    }
```
Comment (madeline-k) [inline src/synthesizer/golang/mod.rs:653]: This is required because the format string for the keys needs to be different depending on if it's for a "real" type or a just a json blob. Json blobs are represented as `map[string]interface{}` in go, which means the keys needs to be wrapped in double quotes `"`.

The way it is written is pretty verbose, and I am new to rust so please let me know if there is a more concise way to write it! I was hoping to do something like the below, 
but this doesn't work because the format string in the `format!` macro MUST be a string literal. There is no way to define it dynamically that I have found. 
```
props.text(format!(
    if structure_is_simple_json { "\"{name}\": " } else { "{name}: " },
    name = golang_identifier(name, IdentifierKind::Exported)
));
```

File: src/synthesizer/golang/mod.rs [hunk 2]
```diff
@@ -620,25 +620,37 @@ impl GolangEmitter for ResourceIr {
...
                             name => format!("&{name}/* FIXME */{{").into(),
                         },
-                        Structure::Simple(cfn) => {
-                            unreachable!("object with simple structure ({:?})", cfn)
+                        Structure::Simple(cfn) => match cfn {
+                            CfnType::Json => {
+                                structure_is_simple_json = true;
+                                "map[string]interface{} {".into()
+                            }
+                            _ => unreachable!("object with simple structure ({:?})", cfn)
```
Comment (madeline-k) [inline src/synthesizer/golang/mod.rs:636]: Now this case should be truly unreachable, because there should never be an `Object` where its structure is one of the basic types.

**Review by HBobertz — APPROVED** [review]
